export default {

  MENU_PROFILE_ON: require('../../assets/icons/profile-on.png'),
  MENU_PROFILE_OFF: require('../../assets/icons/profile-off.png'),
  MENU_TIME_ON: require('../../assets/icons/time-on.png'),
  MENU_TIME_OFF: require('../../assets/icons/time-off.png'),
  MENU_STATS_ON: require('../../assets/icons/stats-on.png'),
  MENU_STATS_OFF: require('../../assets/icons/stats-off.png'),
  MENU_CHAT_ON: require('../../assets/icons/chat-on.png'),
  MENU_CHAT_OFF: require('../../assets/icons/chat-off.png'),
  MENU_MAP_ON: require('../../assets/icons/map-on.png'),
  MENU_MAP_OFF: require('../../assets/icons/map-off.png'),

  ARROW_BACK: require('../../assets/icons/arrow-back.png'),
  CALENDAR: require('../../assets/icons/calendar.png'),
  CHATS: require('../../assets/icons/chats.png'),
  CLOCK: require('../../assets/icons/clock.png'),
  COMMENT_OFF: require('../../assets/icons/comment-no.png'),
  COMMENT_ON: require('../../assets/icons/comment-yes.png'),
  LIKE_OFF: require('../../assets/icons/like-no.png'),
  LIKE_ON: require('../../assets/icons/like-yes.png'),
  CROWN: require('../../assets/icons/crown.png'),
  HEART: require('../../assets/icons/heart.png'),
  MAP: require('../../assets/icons/map.png'),
  ROCKET: require('../../assets/icons/rocket.png'),
  PERSON: require('../../assets/icons/person.png'),
  TROPHY: require('../../assets/icons/trophy.png'),
};
